---
- name: add computer to domain
  hosts: Win11
  tasks:
  - ansible.windows.win_domain_membership:
      dns_domain_name: SRV.ans
      hostname: 
      domain_admin_user: Administrator@SRV.ans
      domain_admin_password: Wasim6624
      state: domain
    register: domain_state
 
  - name: reboot
    ansible.windows.win_reboot: 
    when: domain_state.reboot_required

...
     
